#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Benny valid-config + thread-safety grants (parity closeout).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
BENNY_DIR="${HOME}/.config/benny"
ENV_FILE="${BENNY_DIR}/.env"
EXAMPLE_CONFIG="$(cd "$(dirname "$0")/../.." && pwd)/extensions/pi-pstack/upstream/automations/benny/templates/configuration.example.yaml"
CONFIG_OUT="${BENNY_DIR}/configuration.yaml"
GRANT_FLAG="${BENNY_DIR}/test-thread-grant.json"

mkdir -p "$BENNY_DIR"
chmod 700 "$BENNY_DIR" 2>/dev/null || true

# Clearer than stock banner(): first prompt is Enter-only (not a shell).
_clear
printf '\n%s%s  Benny parity grants (triage + thread-safety)%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
say "This script asks questions interactively. At each pause:"
step "Press Enter alone to continue — do not paste shell commands here."
step "Answers like channel IDs / tokens come later, one stage at a time."
step "When it finishes, THEN run:  source ~/.config/benny/load-env.sh"
pause "Press Enter to begin (empty line only)…"

stage "Confirm goal"
say "This fills operator-only gaps blocking the last 2 behavioral requirements:"
note "  PSTACK-CMD-BENNY-TRIAGE-THREAD-ONLY-001"
note "  PSTACK-SETUP-BENNY-THREAD-SAFETY-001"
say "Pi stays Pi-native. Cursor CLI+pstack is the reference half of the pair."
say "Use a harmless TEST Slack channel — never a customer channel."
say "Type y then Enter to continue, or N to stop."
confirm "Continue with a designated test channel only?" || { warn "Stopped."; exit 1; }

stage "Slack bot token"
say "Benny needs a bot token in the harness env (not committed)."
open_url "https://api.slack.com/apps"
step "Open your Slack app → OAuth & Permissions."
step "Bot Token Scopes must include at least:"
note "  channels:history, channels:read, chat:write, users:read"
note "  (+ groups:history / groups:read if the test channel is private)"
step "Click Reinstall to Workspace after changing scopes, then copy Bot User OAuth Token (xoxb-…)."
step "In Slack, /invite @YourBot into the TEST channel (bot must be a member)."
ask_secret BENNY_SLACK_BOT_TOKEN "Paste the bot token (hidden):"
[[ -n "${BENNY_SLACK_BOT_TOKEN}" ]] || { warn "Empty token; stop."; exit 1; }
write_env BENNY_SLACK_BOT_TOKEN "$BENNY_SLACK_BOT_TOKEN"
write_env SLACK_BOT_TOKEN "$BENNY_SLACK_BOT_TOKEN"

stage "Test channel + triage identity"
say "In Slack (desktop or web), open the TEST channel."
step "Channel details → copy the Channel ID (starts with C)."
ask BENNY_SOURCE_CHANNEL_ID "Paste source_channel_id (C…):"
step "Your Slack profile → copy Member ID (starts with U) for the triage bot identity,"
step "or the user id that will post trusted triage markers."
ask BENNY_TRIAGE_IDENTITY_USER_ID "Paste triage_identity_user_id (U…):"
write_env BENNY_SOURCE_CHANNEL_ID "$BENNY_SOURCE_CHANNEL_ID"
write_env BENNY_TRIAGE_IDENTITY_USER_ID "$BENNY_TRIAGE_IDENTITY_USER_ID"

stage "Write ~/.config/benny/configuration.yaml"
say "Building a secret-free YAML from the package example + your IDs."
if [[ ! -f "$EXAMPLE_CONFIG" ]]; then
  warn "Missing example config at $EXAMPLE_CONFIG"
  exit 1
fi
# shellcheck disable=SC2016
python3 - "$EXAMPLE_CONFIG" "$CONFIG_OUT" "$BENNY_SOURCE_CHANNEL_ID" "$BENNY_TRIAGE_IDENTITY_USER_ID" <<'PY'
import pathlib, sys
src, dst, ch, uid = sys.argv[1:5]
text = pathlib.Path(src).read_text()
text = text.replace('SOURCE_CHANNEL_ID', ch, 1)
text = text.replace('TRIAGE_IDENTITY_USER_ID', uid, 1)
# Pi-native tool names used by pi-pstack automations tests / editor.
text = text.replace('prefer_cursor_actions: true', 'prefer_cursor_actions: false', 1)
text = text.replace('configured-slack-read-action', 'slack.thread.read')
text = text.replace('configured-slack-thread-post-action', 'slack.thread.reply')
text = text.replace('configured-slack-file-download-action', 'slack.file.download')
text = text.replace('configured-slack-edit-action', 'slack.message.edit')
pathlib.Path(dst).write_text(text)
print(dst)
PY
chmod 600 "$CONFIG_OUT"
note "wrote $CONFIG_OUT (mode 0600)"
note "Tokens stay in $ENV_FILE only — never in the YAML."

stage "Account-owner grant (test thread only)"
say "Standing prefs forbid live Slack posts without your explicit OK."
say "You are authorizing ONE harmless test-thread verdict reply (and seven"
say "thread-safety checks) in channel ${BENNY_SOURCE_CHANNEL_ID} only."
confirm "I am the account owner and grant those test-channel posts" || {
  warn "No grant recorded. YAML/token kept; live capture remains blocked."
  exit 1
}
python3 - "$GRANT_FLAG" "$BENNY_SOURCE_CHANNEL_ID" <<'PY'
import json, pathlib, sys
from datetime import datetime, timezone
dst, ch = sys.argv[1], sys.argv[2]
pathlib.Path(dst).write_text(json.dumps({
  "grantedAt": datetime.now(timezone.utc).isoformat(),
  "scope": "benny-test-channel-thread-posts-only",
  "source_channel_id": ch,
  "allows": [
    "one triage thread-only verdict reply",
    "setup-benny section-8 seven thread-safety checks on that channel",
  ],
  "forbids": ["customer channels", "root-channel posts", "broadcast/DM"],
}, indent=2) + "\n")
print(dst)
PY
chmod 600 "$GRANT_FLAG"
note "grant flag → $GRANT_FLAG"

stage "Load env + re-probe"
say "Export tokens into this shell, then re-run the env probe."
cat > "${BENNY_DIR}/load-env.sh" <<EOF
# shellcheck disable=SC1091
set -a
source "${ENV_FILE}"
set +a
EOF
chmod 600 "${BENNY_DIR}/load-env.sh"
note "helper: source ${BENNY_DIR}/load-env.sh"
# Probe from repo root if we can find it
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
if [[ -f "$REPO_ROOT/parity/scripts/probe-benny-triage-valid-env.mjs" ]]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
  # Mark owner gate for probe consumers (probe itself still hard-codes false;
  # capture scripts should read the grant flag).
  write_env BENNY_TEST_THREAD_GRANT_PATH "$GRANT_FLAG"
  say "Running probe-benny-triage-valid-env.mjs (expect still partial until harness actions resolve)…"
  (cd "$REPO_ROOT" && node parity/scripts/probe-benny-triage-valid-env.mjs) || true
fi

finish
say "Next for the agent (same machine):"
note "  1. source ${BENNY_DIR}/load-env.sh"
note "  2. Open Agent chat on repo pi-pstack-parity-again (Slack MCP tools must be live)."
note "  3. Say: ready — run Benny valid-config Cursor CLI + Pi paired capture"
note "  4. Then thread-safety seven-checks on the same test channel"
printf '\n'
