import { readFileSync, writeFileSync } from 'node:fs';

// Usage: node scripts/snapshot-catalog.mjs <fetchAvailableModels response.json>
// Writes the agent-model subset that the provider lists before the first login.
const source = process.argv[2];
if (!source) throw new Error('Pass the path of a saved fetchAvailableModels response');
const data = JSON.parse(readFileSync(source, 'utf8'));
const fields = ['displayName', 'supportsImages', 'supportsThinking', 'thinkingBudget', 'thinkingLevel', 'maxTokens', 'maxOutputTokens'];
const agentModelSorts = data.agentModelSorts.map(({ groups }) => ({ groups: groups.map(({ modelIds }) => ({ modelIds })) }));
const ids = agentModelSorts.flatMap(({ groups }) => groups.flatMap(({ modelIds }) => modelIds));
const models = Object.fromEntries(ids.map((id) => [id, Object.fromEntries(fields.filter((field) => field in data.models[id]).map((field) => [field, data.models[id][field]]))]));
const deprecatedModelIds = Object.fromEntries(Object.entries(data.deprecatedModelIds ?? {}).map(([old, { newModelId }]) => [old, { newModelId }]));
const snapshot = { agentModelSorts, deprecatedModelIds, models };
const header = '// Generated by scripts/snapshot-catalog.mjs from a live fetchAvailableModels response.\n';
writeFileSync(new URL('../src/catalog-snapshot.ts', import.meta.url), `${header}export default ${JSON.stringify(snapshot, null, 2)};\n`);
