const dir = 'skills/poteto-mode/scripts';
const L = (...lines) => lines.join('\n');

const noChecksReason =
  '{ readonly kind: "no-checks-unconfirmed"; readonly readings: number; readonly required: number }';

const types = {
  path: `${dir}/watch-pr/types.ts`,
  edits: [
    [
      L('  | {', '      readonly kind: "invalid-context-url";'),
      L(
        '  | {',
        '      readonly kind: "gh-missing";',
        '      readonly retryable: false;',
        '      readonly detail: string;',
        '    }',
        '  | {',
        '      readonly kind: "bootstrap-failed";',
        '      readonly retryable: false;',
        '      readonly detail: string;',
        '    }',
        '  | {',
        '      readonly kind: "stack-cycle";',
        '      readonly retryable: false;',
        '      readonly detail: string;',
        '    }',
        '  | {',
        '      readonly kind: "invalid-context-url";',
      ),
      'Add non-retryable failure kinds for a missing gh, a failed dependency install, and a cyclic stack so each reaches the exit-7 BLOCKER path.',
    ],
    [
      '        | { readonly kind: "merge-queue"; readonly unmergedCount: number };',
      L('        | { readonly kind: "merge-queue"; readonly unmergedCount: number }', `        | ${noChecksReason};`),
      'Give a zero-check PR that has not yet persisted across polls its own WAITING reason.',
    ],
    [
      '    | { readonly kind: "status-unavailable"; readonly failure: QueryFailure }',
      L('    | { readonly kind: "status-unavailable"; readonly failure: QueryFailure }', `    | ${noChecksReason}`),
      'Let the deadline report a zero-check PR that never confirmed.',
    ],
  ],
};

const runOriginal = L(
  'function run(argv: readonly [string, ...string[]]): Promise<CommandResult> {',
  '  return new Promise((resolve, reject) => {',
  '    const child = spawn(argv[0], argv.slice(1), {',
  '      stdio: ["ignore", "pipe", "pipe"],',
  '    });',
  '    let stdout = "";',
  '    let stderr = "";',
  '    child.stdout.setEncoding("utf8");',
  '    child.stderr.setEncoding("utf8");',
  '    child.stdout.on("data", (chunk: string) => {',
  '      stdout += chunk;',
  '    });',
  '    child.stderr.on("data", (chunk: string) => {',
  '      stderr += chunk;',
  '    });',
  '    child.on("error", reject);',
  '    child.on("close", (code) => resolve({ code: code ?? -1, stdout, stderr }));',
  '  });',
  '}',
);

const runReplacement = L(
  'const DEFAULT_COMMAND_TIMEOUT_SECONDS = 120;',
  'function commandTimeoutMs(): number {',
  '  const seconds = Number(process.env.WATCH_PR_COMMAND_TIMEOUT_SECONDS);',
  '  return (',
  '    (Number.isFinite(seconds) && seconds > 0',
  '      ? seconds',
  '      : DEFAULT_COMMAND_TIMEOUT_SECONDS) * 1_000',
  '  );',
  '}',
  'function spawnFailure(argv: readonly string[], error: unknown): Error {',
  '  const absent =',
  '    error instanceof Error &&',
  '    ((error as NodeJS.ErrnoException).code === "ENOENT" ||',
  '      /not found/i.test(error.message));',
  '  if (absent && argv[0] === "gh")',
  '    return new WatcherQueryError({',
  '      kind: "gh-missing",',
  '      retryable: false,',
  '      detail:',
  '        "gh was not found on PATH; install the GitHub CLI and run gh auth login",',
  '    });',
  '  return error instanceof Error ? error : new Error(String(error));',
  '}',
  'function launch(',
  '  argv: readonly [string, ...string[]],',
  '  resolve: (result: CommandResult) => void,',
  '  reject: (error: unknown) => void',
  '): void {',
  '  const child = spawn(argv[0], argv.slice(1), {',
  '    stdio: ["ignore", "pipe", "pipe"],',
  '  });',
  '  let stdout = "";',
  '  let stderr = "";',
  '  child.stdout.setEncoding("utf8");',
  '  child.stderr.setEncoding("utf8");',
  '  child.stdout.on("data", (chunk: string) => {',
  '    stdout += chunk;',
  '  });',
  '  child.stderr.on("data", (chunk: string) => {',
  '    stderr += chunk;',
  '  });',
  '  const timer = setTimeout(() => {',
  '    child.kill("SIGKILL");',
  '    reject(',
  '      new WatcherQueryError({',
  '        kind: "command-exit",',
  '        retryable: true,',
  '        code: -1,',
  '        detail: `${argv[0]} ${argv.slice(1, 4).join(" ")} timed out after ${commandTimeoutMs() / 1_000}s`,',
  '      })',
  '    );',
  '  }, commandTimeoutMs());',
  '  child.on("error", (error) => {',
  '    clearTimeout(timer);',
  '    reject(spawnFailure(argv, error));',
  '  });',
  '  child.on("close", (code) => {',
  '    clearTimeout(timer);',
  '    resolve({ code: code ?? -1, stdout, stderr });',
  '  });',
  '}',
  'function run(argv: readonly [string, ...string[]]): Promise<CommandResult> {',
  '  return new Promise((resolve, reject) => {',
  '    try {',
  '      launch(argv, resolve, reject);',
  '    } catch (error) {',
  '      reject(spawnFailure(argv, error));',
  '    }',
  '  });',
  '}',
);

const remoteOriginal = L(
  '  if (normalized.startsWith("git@github.com:"))',
  '    normalized = `https://github.com/${normalized.slice(15)}`;',
  '  if (normalized.startsWith("ssh://git@github.com/"))',
  '    normalized = `https://github.com/${normalized.slice(21)}`;',
);

const remoteReplacement = L(
  '  normalized = normalized.replace(/^git@([^:/]+):/, "https://$1/");',
  '  normalized = normalized.replace(/^ssh:\\/\\/git@([^/:]+)\\//, "https://$1/");',
);

const originRepoOriginal = L(
  '    const result = await run(["git", "remote", "get-url", "origin"]);',
  '    return result.code === 0 ? parseRemote(result.stdout) : null;',
);

const originRepoReplacement = L(
  '    try {',
  '      const result = await run(["git", "remote", "get-url", "origin"]);',
  '      return result.code === 0 ? parseRemote(result.stdout) : null;',
  '    } catch {',
  '      return null;',
  '    }',
);

const openListOriginal = L(
  '    const value = await runJson([',
  '      "gh",',
  '      "pr",',
  '      "list",',
  '      "--repo",',
  '      `${repository.owner}/${repository.repo}`,',
  '      "--state",',
  '      "open",',
  '      "--limit",',
  '      "300",',
  '      "--json",',
  '      "number,headRefName,baseRefName",',
  '    ]);',
  '    return list(value, "open PRs").map((item, index) => {',
);

const openListReplacement = L(
  '    const value = await listOpenPullRequests(repository);',
  '    return value.map((item, index) => {',
);

const githubHelpers = L(
  'const OPEN_PR_LIMIT_CEILING = 10_000;',
  'async function listOpenPullRequests(',
  '  repository: T.Repository',
  '): Promise<readonly unknown[]> {',
  '  let limit = 300;',
  '  while (true) {',
  '    const items = list(',
  '      await runJson([',
  '        "gh",',
  '        "pr",',
  '        "list",',
  '        "--repo",',
  '        `${repository.owner}/${repository.repo}`,',
  '        "--state",',
  '        "open",',
  '        "--limit",',
  '        String(limit),',
  '        "--json",',
  '        "number,headRefName,baseRefName",',
  '      ]),',
  '      "open PRs"',
  '    );',
  '    if (items.length < limit) return items;',
  '    if (limit >= OPEN_PR_LIMIT_CEILING)',
  '      throw new WatcherQueryError({',
  '        kind: "missing-key",',
  '        retryable: true,',
  '        detail: `open PR list was truncated at ${limit}`,',
  '      });',
  '    limit = Math.min(limit * 2, OPEN_PR_LIMIT_CEILING);',
  '  }',
  '}',
  'function nextThreadCursor(pageInfo: unknown, seen: Set<string>): string | null {',
  '  const info = record(pageInfo, "reviewThreads.pageInfo");',
  '  if (typeof info.hasNextPage !== "boolean")',
  '    missing("reviewThreads.pageInfo.hasNextPage", info.hasNextPage);',
  '  if (!info.hasNextPage) return null;',
  '  const reference = optionalString(',
  '    info.endCursor,',
  '    "reviewThreads.pageInfo.endCursor"',
  '  );',
  '  if (reference === null || reference === "" || seen.has(reference))',
  '    missing("reviewThreads.pageInfo.endCursor", info.endCursor);',
  '  seen.add(reference);',
  '  return reference;',
  '}',
  'async function allReviewThreadPages(context: T.PrContext): Promise<unknown> {',
  '  const nodes: unknown[] = [];',
  '  const seen = new Set<string>();',
  '  let after: string | null = null;',
  '  do {',
  '    const argv = graphqlArgs(REVIEW_THREADS_QUERY, context);',
  '    if (after !== null) argv.push("-f", `after=${after}`);',
  '    const connection = record(',
  '      at(await runJson(argv), [',
  '        "data",',
  '        "repository",',
  '        "pullRequest",',
  '        "reviewThreads",',
  '      ]),',
  '      "reviewThreads"',
  '    );',
  '    nodes.push(...list(connection.nodes, "reviewThreads.nodes"));',
  '    after = nextThreadCursor(connection.pageInfo, seen);',
  '  } while (after !== null);',
  '  return { data: { repository: { pullRequest: { reviewThreads: { nodes } } } } };',
  '}',
  '',
  'export class GhGitHubReader implements T.GitHubReader {',
);

const threadsOriginal = L(
  '    return parseReviewThreads(',
  '      await runJson(graphqlArgs(REVIEW_THREADS_QUERY, context))',
  '    );',
);

const threadsReplacement = L('    return parseReviewThreads(await allReviewThreadPages(context));');

const downOriginal = L(
  '  const down: T.OpenPullRequest[] = [];',
  '  let current = start;',
  '  while (byHead.has(current.baseRefName)) {',
  '    const parent = byHead.get(current.baseRefName);',
  '    if (parent === undefined) break;',
  '    down.push(parent);',
  '    current = parent;',
  '  }',
);

const downReplacement = L(
  '  const down: T.OpenPullRequest[] = [];',
  '  const visited = new Set<T.PrNumber>([start.number]);',
  '  let current = start;',
  '  while (byHead.has(current.baseRefName)) {',
  '    const parent = byHead.get(current.baseRefName);',
  '    if (parent === undefined) break;',
  '    if (visited.has(parent.number))',
  '      throw new WatcherQueryError({',
  '        kind: "stack-cycle",',
  '        retryable: false,',
  '        detail: `stack discovery found a cycle: PR #${parent.number} is both above and below PR #${start.number}`,',
  '      });',
  '    visited.add(parent.number);',
  '    down.push(parent);',
  '    current = parent;',
  '  }',
);

const checksSignatureOriginal = L(
  'export async function resolveChecks(',
  '  reader: T.GitHubReader,',
  '  context: T.PrContext',
  '): Promise<T.CheckRead> {',
);

const checksSignatureReplacement = L(
  'const NO_CHECKS_PLACEHOLDER: T.Check = {',
  '  kind: "skipped",',
  '  name: "no checks reported",',
  '  reportedState: "NONE",',
  '  description: "gh pr checks and the GraphQL rollup both report zero checks",',
  '  link: "",',
  '  workflow: "",',
  '};',
  'export function isNoChecksReading(checks: readonly T.Check[]): boolean {',
  '  return checks.length === 1 && checks[0] === NO_CHECKS_PLACEHOLDER;',
  '}',
  'function confirmsNoChecks(fast: T.ChecksFastPath): boolean {',
  '  if (fast.kind === "checks") return true;',
  '  return fast.exitCode === 1 && /no checks reported/i.test(fast.stderr);',
  '}',
  'export async function resolveChecks(',
  '  reader: T.GitHubReader,',
  '  context: T.PrContext,',
  '  allowEmpty = false',
  '): Promise<T.CheckRead> {',
);

const fallbackOriginal = '  if (fallback !== null) return { source: "graphql-rollup", checks: fallback };';
const fallbackReplacement = L(
  fallbackOriginal,
  '  if (allowEmpty && confirmsNoChecks(fast))',
  '    return { source: "graphql-rollup", checks: [NO_CHECKS_PLACEHOLDER] };',
);

const hostCheck = (tail) =>
  L(
    '      url.hostname !== "github.com" ||',
    '      url.port ||',
    '      url.username ||',
    '      url.password ||',
    '      url.search ||',
    '      url.hash ||',
    `      parts.length !== ${tail}`,
  );
const hostCheckKnown = (tail) => hostCheck(tail).replace('url.hostname !== "github.com"', '!isKnownHost(url.hostname)');

const github = {
  path: `${dir}/watch-pr/github.ts`,
  edits: [
    [
      'reviewThreads(first: 100) {\\n        nodes {',
      'reviewThreads(first: 100, after: $after) {\\n        pageInfo {\\n          hasNextPage\\n          endCursor\\n        }\\n        nodes {',
      'Request pageInfo and accept a reference so review threads can be paged.',
    ],
    [
      'query ReviewThreads($owner: String!, $repo: String!, $pr: Int!) {',
      'query ReviewThreads($owner: String!, $repo: String!, $pr: Int!, $after: String) {',
      'Declare the review thread reference variable.',
    ],
    [runOriginal, runReplacement, 'Bound every gh and git subprocess with a timeout and report a missing gh as a typed non-retryable failure instead of an uncaught crash.'],
    [
      'function parseRemote(value: string): T.Repository | null {',
      L(
        'function isKnownHost(hostname: string): boolean {',
        '  const configured = process.env.GH_HOST?.trim().toLowerCase();',
        '  return (',
        '    hostname === "github.com" ||',
        '    (configured !== undefined && configured !== "" && hostname === configured)',
        '  );',
        '}',
        'function parseRemote(value: string): T.Repository | null {',
      ),
      'Accept the host gh is configured for (GH_HOST) as well as github.com.',
    ],
    [remoteOriginal, remoteReplacement, 'Normalize scp and ssh remotes for any host, then let the host check decide.'],
    [hostCheck(2), hostCheckKnown(2), 'Apply the configured-host rule to origin remotes.'],
    [hostCheck(4), hostCheckKnown(4), 'Apply the configured-host rule to pull request URLs.'],
    [originRepoOriginal, originRepoReplacement, 'Treat a missing or unrunnable git as no origin so context falls back to gh.'],
    [openListOriginal, openListReplacement, 'Read open PRs through a helper that keeps raising the limit until the list is not full.'],
    ['\nexport class GhGitHubReader implements T.GitHubReader {', `\n${githubHelpers}`, 'Add the open PR paging and review thread paging helpers.'],
    [threadsOriginal, threadsReplacement, 'Fetch every review thread page so an unresolved thread past 100 cannot be hidden.'],
    [downOriginal, downReplacement, 'Fail closed on a cyclic stack instead of looping forever.'],
    [checksSignatureOriginal, checksSignatureReplacement, 'Let a caller read a confirmed zero-check PR as one skipped placeholder.'],
    [fallbackOriginal, fallbackReplacement, 'Return the zero-check placeholder only when gh confirms there are no checks.'],
  ],
};

const queuedTimeoutHelper = L(
  'function queuedTimeout(stamp: VerdictStamp, state: QueueState): T.TimeoutVerdict {',
  '  const unmerged = state.queue.filter(',
  '    (context) => state.snapshots.get(context.number)?.kind !== "merged"',
  '  );',
  '  return stamp({',
  '    kind: "TIMEOUT",',
  '    terminal: true,',
  '    exitCode: 5,',
  '    reason: {',
  '      kind: "queued-stack",',
  '      frontier: unmerged[0] ?? state.queue[0],',
  '      unmergedCount: unmerged.length,',
  '    },',
  '  });',
  '}',
  'export async function runQueued(args: {',
);

const noChecksStreakHelpers = L(
  'const NO_CHECKS_READINGS_REQUIRED = 2;',
  'type Streaks = ReadonlyMap<T.PrNumber, { sha: string | null; count: number }>;',
  'function nextStreaks(prev: Streaks, rows: readonly T.PrSnapshot[]): Streaks {',
  '  const next = new Map<T.PrNumber, { sha: string | null; count: number }>();',
  '  for (const row of rows) {',
  '    if (row.kind !== "open" || !isNoChecksReading(row.ci.all)) continue;',
  '    const sha = row.facts.headRefOid;',
  '    const before = prev.get(row.context.number);',
  '    const same = before !== undefined && sha !== null && before.sha === sha;',
  '    next.set(row.context.number, { sha, count: same ? before.count + 1 : 1 });',
  '  }',
  '  return next;',
  '}',
  'function unconfirmed(rows: readonly T.PrSnapshot[], streaks: Streaks) {',
  '  for (const row of rows) {',
  '    const streak = streaks.get(row.context.number);',
  '    if (streak !== undefined && (streak.count < NO_CHECKS_READINGS_REQUIRED || streak.sha === null))',
  '      return { context: row.context, readings: streak.count };',
  '  }',
  '  return null;',
  '}',
  'export async function runSimple(args: {',
);

const noChecksGate = L(
  '    streaks = nextStreaks(streaks, complete);',
  '    const wait = decision.kind === "waiting" ? null : unconfirmed(complete, streaks);',
  '    if (wait !== null) {',
  '      const reason = { kind: "no-checks-unconfirmed", readings: wait.readings, required: NO_CHECKS_READINGS_REQUIRED } as const;',
  '      args.dependencies.emit(stamp({ kind: "WAITING", terminal: false, frontier: wait.context, reason }));',
  '      const onDeadline = () => stamp({ kind: "TIMEOUT", terminal: true, exitCode: 5, reason });',
  '      return { kind: "sleep", seconds: args.options.interval, onDeadline };',
  '    }',
  '    if (decision.kind === "ready" || decision.kind === "merged")',
);

const policy = {
  path: `${dir}/watch-pr/policy.ts`,
  edits: [
    [
      '  const checks = await resolveChecks(args.reader, args.context);',
      L(
        '  const checks = await resolveChecks(',
        '    args.reader,',
        '    args.context,',
        '    facts.mergeStateStatus !== "BLOCKED" &&',
        '      facts.mergeStateStatus !== "UNKNOWN"',
        '  );',
      ),
      'Read a PR with zero checks as having no required checks unless GitHub reports it blocked or still computing.',
    ],
    ['import { WatcherQueryError, resolveChecks } from "./github.ts";', 'import { WatcherQueryError, isNoChecksReading, resolveChecks } from "./github.ts";', 'Import the zero-check reading predicate.'],
    ['export async function runSimple(args: {', noChecksStreakHelpers, 'Track consecutive same-head zero-check readings per PR.'],
    [
      L('  const stamp = verdictFactory(args.dependencies.clock, args.mode);', '  const step = async (): Promise<StepResult<T.TerminalVerdict>> => {'),
      L('  const stamp = verdictFactory(args.dependencies.clock, args.mode);', '  let streaks: Streaks = new Map();', '  const step = async (): Promise<StepResult<T.TerminalVerdict>> => {'),
      'Keep the zero-check streak across polls of one run.',
    ],
    ['    if (decision.kind === "ready" || decision.kind === "merged")', noChecksGate, 'Fail closed: update the streak, then wait until a zero-check reading persists across two polls at one head SHA.'],
    ['export async function runQueued(args: {', queuedTimeoutHelper, 'Build the queued-stack TIMEOUT verdict in one place.'],
    [
      L('    state = planQueue(state, args.dependencies.clock.now());', '    if (state.work === null) {'),
      L(
        '    state = planQueue(state, args.dependencies.clock.now());',
        '    if (',
        '      state.work !== null &&',
        '      deadlinePassed(',
        '        state.startedAt,',
        '        args.options,',
        '        args.dependencies.clock.now()',
        '      )',
        '    )',
        '      return { kind: "terminal", verdict: queuedTimeout(stamp, state) };',
        '    if (state.work === null) {',
      ),
      'Check the queued deadline between sweep reads so a long sweep cannot overshoot --timeout.',
    ],
    [
      '        return { kind: "sleep", seconds: args.options.interval };',
      L(
        '        return {',
        '          kind: "sleep",',
        '          seconds: args.options.interval,',
        '          onDeadline: () => queuedTimeout(stamp, state),',
        '        };',
      ),
      'Give the queued waiting sleep a deadline hook like the single and stack runner has.',
    ],
  ],
};

const render = {
  path: `${dir}/watch-pr/render.ts`,
  edits: [
    [
      'import type * as T from "./types.ts";',
      L('import { isNoChecksReading } from "./github.ts";', 'import type * as T from "./types.ts";'),
      'Import the zero-check reading predicate.',
    ],
    [
      L('    case "ci-clean":', '      return "✅";'),
      L('    case "ci-clean":', '      return isNoChecksReading(row.ci.all) ? "\u2796 no checks" : "✅";'),
      'Show a zero-check PR as having no checks instead of a passing mark.',
    ],
    [
      L('    case "WAITING":', '      return verdict.reason.kind === "pending-checks"'),
      L(
        '    case "WAITING":',
        '      if (verdict.reason.kind === "no-checks-unconfirmed")',
        '        return `WAITING: frontier=#${verdict.frontier.number}; no checks reported (${verdict.reason.readings}/${verdict.reason.required} readings at this head); waiting to confirm none are coming\\n`;',
        '      return verdict.reason.kind === "pending-checks"',
      ),
      'Render the zero-check WAITING reason.',
    ],
    [
      '      if (verdict.reason.kind === "status-unavailable")',
      L(
        '      if (verdict.reason.kind === "no-checks-unconfirmed")',
        '        return "TIMEOUT: no checks reported and none confirmed absent\\n";',
        '      if (verdict.reason.kind === "status-unavailable")',
      ),
      'Render the zero-check TIMEOUT reason.',
    ],
  ],
};

const bootstrapOriginal = L(
  'export function ensureDependenciesInstalled(): void {',
  '  const installKey = currentInstallKey();',
  '  if (',
  '    existsSync(commanderPackagePath) &&',
  '    existsSync(installKeyPath) &&',
  '    readFileSync(installKeyPath, "utf8").trim() === installKey',
  '  ) {',
  '    return;',
  '  }',
  '',
  '  const result = Bun.spawnSync(',
  '    [process.execPath, "install", "--frozen-lockfile"],',
  '    { cwd: scriptsDirectory }',
  '  );',
  '  if (result.exitCode !== 0) {',
  '    process.stdout.write(result.stdout);',
  '    process.stderr.write(result.stderr);',
  '    throw new Error(',
  '      `bun install --frozen-lockfile exited with status ${result.exitCode}`',
  '    );',
  '  }',
  '  if (!existsSync(commanderPackagePath)) {',
  '    throw new Error(',
  '      "bun install --frozen-lockfile completed without installing commander"',
  '    );',
  '  }',
  '',
  '  writeFileSync(installKeyPath, `${installKey}\\n`);',
  '',
  '  const restarted = Bun.spawnSync([process.execPath, ...process.argv.slice(1)], {',
  '    cwd: process.cwd(),',
  '    env: process.env,',
  '    stdin: "inherit",',
  '    stdout: "inherit",',
  '    stderr: "inherit",',
  '  });',
  '  process.exit(restarted.exitCode ?? 1);',
  '}',
);

const bootstrapReplacement = L(
  'const installLockPath = join(scriptsDirectory, ".poteto-mode-tools-install.lock");',
  'const lockPollMilliseconds = 100;',
  'const lockWaitMilliseconds = 5 * 60 * 1000;',
  '',
  'function isInstalled(installKey: string): boolean {',
  '  return (',
  '    existsSync(commanderPackagePath) &&',
  '    existsSync(installKeyPath) &&',
  '    readFileSync(installKeyPath, "utf8").trim() === installKey',
  '  );',
  '}',
  '',
  'function processAlive(pid: number): boolean {',
  '  try {',
  '    process.kill(pid, 0);',
  '    return true;',
  '  } catch (error) {',
  '    return (error as NodeJS.ErrnoException).code === "EPERM";',
  '  }',
  '}',
  '',
  'function lockIsOld(): boolean {',
  '  try {',
  '    return Date.now() - statSync(installLockPath).mtimeMs > lockWaitMilliseconds;',
  '  } catch {',
  '    return false;',
  '  }',
  '}',
  '',
  'function lockIsStale(): boolean {',
  '  let pid = Number.NaN;',
  '  try {',
  '    pid = Number(readFileSync(join(installLockPath, "pid"), "utf8"));',
  '  } catch {}',
  '  return Number.isInteger(pid) && pid > 0 ? !processAlive(pid) : lockIsOld();',
  '}',
  '',
  'function tryAcquireInstallLock(): boolean {',
  '  try {',
  '    mkdirSync(installLockPath);',
  '    writeFileSync(join(installLockPath, "pid"), String(process.pid));',
  '    return true;',
  '  } catch (error) {',
  '    if ((error as NodeJS.ErrnoException).code === "EEXIST") return false;',
  '    throw error;',
  '  }',
  '}',
  '',
  'function acquireInstallLock(installKey: string): boolean {',
  '  const deadline = Date.now() + lockWaitMilliseconds;',
  '  while (!tryAcquireInstallLock()) {',
  '    if (isInstalled(installKey)) return false;',
  '    if (lockIsStale()) rmSync(installLockPath, { recursive: true, force: true });',
  '    else if (Date.now() > deadline)',
  '      throw new Error(',
  '        "timed out waiting for another process to finish installing dependencies"',
  '      );',
  '    else Bun.sleepSync(lockPollMilliseconds);',
  '  }',
  '  return true;',
  '}',
  '',
  'interface SpawnResult {',
  '  readonly exitCode: number;',
  '  readonly stdout: string;',
  '  readonly stderr: string;',
  '}',
  '',
  'const readStream = (stream: unknown): Promise<string> =>',
  '  stream instanceof ReadableStream',
  '    ? new Response(stream).text()',
  '    : Promise.resolve("");',
  '',
  'async function spawnForwarding(',
  '  argv: string[],',
  '  cwd: string,',
  '  inherit: boolean',
  '): Promise<SpawnResult> {',
  '  const child = inherit',
  '    ? Bun.spawn(argv, {',
  '        cwd,',
  '        env: process.env,',
  '        stdin: "inherit",',
  '        stdout: "inherit",',
  '        stderr: "inherit",',
  '      })',
  '    : Bun.spawn(argv, { cwd, stdout: "pipe", stderr: "pipe" });',
  '  const forwarders = (["SIGINT", "SIGTERM"] as const).map((signal) => {',
  '    const forward = (): void => {',
  '      child.kill(signal);',
  '    };',
  '    process.on(signal, forward);',
  '    return [signal, forward] as const;',
  '  });',
  '  const [stdout, stderr] = await Promise.all([',
  '    readStream(child.stdout),',
  '    readStream(child.stderr),',
  '  ]);',
  '  await child.exited;',
  '  for (const [signal, forward] of forwarders) process.off(signal, forward);',
  '  const signalled = child.signalCode;',
  '  return {',
  '    exitCode:',
  '      child.exitCode ??',
  '      (signalled === null ? 1 : 128 + (constants.signals[signalled] ?? 0)),',
  '    stdout,',
  '    stderr,',
  '  };',
  '}',
  '',
  'async function installDependencies(installKey: string): Promise<void> {',
  '  const result = await spawnForwarding(',
  '    [process.execPath, "install", "--frozen-lockfile"],',
  '    scriptsDirectory,',
  '    false',
  '  );',
  '  if (result.exitCode !== 0) {',
  '    process.stderr.write(result.stdout);',
  '    process.stderr.write(result.stderr);',
  '    throw new Error(',
  '      `bun install --frozen-lockfile exited with status ${result.exitCode}`',
  '    );',
  '  }',
  '  if (!existsSync(commanderPackagePath)) {',
  '    throw new Error(',
  '      "bun install --frozen-lockfile completed without installing commander"',
  '    );',
  '  }',
  '  writeFileSync(installKeyPath, `${installKey}\\n`);',
  '}',
  '',
  'export async function ensureDependenciesInstalled(): Promise<void> {',
  '  const installKey = currentInstallKey();',
  '  if (isInstalled(installKey)) return;',
  '  if (acquireInstallLock(installKey)) {',
  '    try {',
  '      if (!isInstalled(installKey)) await installDependencies(installKey);',
  '    } finally {',
  '      rmSync(installLockPath, { recursive: true, force: true });',
  '    }',
  '  }',
  '  const restarted = await spawnForwarding(',
  '    [process.execPath, ...process.argv.slice(1)],',
  '    process.cwd(),',
  '    true',
  '  );',
  '  process.exit(restarted.exitCode);',
  '}',
);

const bootstrap = {
  path: `${dir}/bootstrap.ts`,
  edits: [
    [
      'import { existsSync, readFileSync, writeFileSync } from "node:fs";',
      L(
        'import {',
        '  existsSync,',
        '  mkdirSync,',
        '  readFileSync,',
        '  rmSync,',
        '  statSync,',
        '  writeFileSync,',
        '} from "node:fs";',
        'import { constants } from "node:os";',
      ),
      'Import the filesystem and signal helpers the locked, signal-forwarding install needs.',
    ],
    [bootstrapOriginal, bootstrapReplacement, 'Serialize the install behind an exclusive lock directory, forward SIGINT and SIGTERM to the install and the re-exec child, and wait for a concurrent install instead of racing it.'],
  ],
};

const launcher = {
  path: `${dir}/watch-pr/watch-pr`,
  edits: [
    [
      L('ensureDependenciesInstalled();', 'const { main } = await import("./cli.ts");'),
      L(
        'try {',
        '  await ensureDependenciesInstalled();',
        '} catch (error) {',
        '  const { statusQueryVerdict, verdictFactory } = await import("./policy.ts");',
        '  const { renderJson } = await import("./render.ts");',
        '  const clock = {',
        '    now: () => performance.now() / 1_000,',
        '    observedAt: () => new Date().toISOString(),',
        '    sleep: async () => {},',
        '  };',
        '  const detail = error instanceof Error ? error.message : String(error);',
        '  const verdict = statusQueryVerdict(verdictFactory(clock, "single"), 1, {',
        '    kind: "bootstrap-failed",',
        '    retryable: false,',
        '    detail,',
        '  });',
        '  process.stdout.write(renderJson(verdict));',
        '  process.exit(verdict.exitCode);',
        '}',
        'const { main } = await import("./cli.ts");',
      ),
      'Render a failed dependency install as the documented exit-7 BLOCKER instead of an uncaught throw.',
    ],
  ],
};

const orch = {
  path: `${dir}/orch/orch.ts`,
  edits: [
    [
      L('ensureDependenciesInstalled();', 'const {'),
      L('if (import.meta.main) await ensureDependenciesInstalled();', 'const {'),
      'Install dependencies only when orch.ts is the entry point so importing it has no side effect.',
    ],
  ],
};

export default [types, github, policy, render, bootstrap, launcher, orch];
