import { join } from 'node:path';
import type { ExtensionContext } from '@earendil-works/pi-coding-agent';
import { modelConfigPath } from './models.ts';

export function hostInstructions(root: string, ctx: ExtensionContext, rule: string): string {
  return [
      'pstack pi host contract. Follow the bundled workflow instructions in full. Preserve their gates and report missing dependencies.',
      `Bundled skills: ${join(root, 'skills')}. Immutable source including agents and dormant Benny pack: ${join(root, 'upstream')}.`,
      'Workflow aliases are Pi prompt templates. When one requests a skill, read its SKILL.md in full from the bundled skills directory and resolve references relative to that skill directory. /bro is a standalone prompt template. Only /poteto-mode, /setup-pstack, and /pstack are executable extension commands.',
      `team-kit 1.2.0 is bundled at ${join(root, 'upstream-team-kit')}. Its 18 skills, including deslop, control-cli, control-ui and verify-this, are in the same generated skills directory. Read the relevant SKILL.md in full before applying it. Its two rules remain archived, matching observed Reference plugin delivery.`,
      `Read model role overrides at ${modelConfigPath()}. This is the Pi mapping of ~/.upstream/rules/pstack-models.mdc. The active rule follows:\n${rule || 'No override. Upstream defaults remain requests, not confirmed available models.'}`,
      'Task, TaskOutput, TaskMessage, TaskStop implement local delegation. Use exact available provider/model IDs, optionally :thinking. auto and inherit-parent inherit the parent. Unavailable Reference slugs fail with available choices. Follow the source fallback policy and report any model change.',
      'Cloud Task execution is unavailable. Never silently replace a required cloud task with local execution. Readonly workers have restricted tools, not an OS sandbox. Agent-mode workers use installed Pi extensions; their tool availability depends on those extensions.',
      'TodoWrite keeps the verbatim ordered playbook steps. AskQuestion is available only with interactive or RPC dialogs. Cancellation is not approval.',
      'pstack_mode changes sticky mode on explicit user entry or opt-out. Recognize natural-language user requests through that tool, not quoted examples. Only apply the active mode to tasks matching its own scope.',
      `Workspace Pi session directory: ${ctx.sessionManager.getSessionDir()}. Task child transcripts: ${join(ctx.sessionManager.getSessionDir(), 'pstack-workers', '<parent-session-id>')}. Transcript-reading skills use these directories. Use pstack_context for this Pi session and workspace history. Reference chat links in upstream prose are source-host references; do not invent them or read other workspaces to fill gaps.`,
      'Task also supports the bundled ci-watcher and thermo-nuclear-code-quality-review personas. ci-watcher inherits the parent model unless the caller supplies a configured Pi model, matching observed Reference plugin behavior. No model is silently substituted. The kit references Reference built-in shell and explore personas whose contracts are not published here; these remain unsupported. Collect the required diff and file contents with available tools before invoking the thermo review persona.',
      'control-cli and control-ui provide local harness instructions, not installed terminal or browser tooling. Discover and use the project tools as those skills require. pr-review-canvas assets are bundled, but Pi has no Reference in-app browser. Use available local browser tooling only when it satisfies the workflow. workflow-from-chats can inspect Pi workspace history through pstack_context; identify that corpus and cite real parent session IDs without exposing private transcript paths or inventing Reference links.',
      'Reference /loop, /goal, cloud hosting, /automate editor, server-synced create-skill and Grok Bot routines are not implemented here. The bundled loop-on-ci skill watches GitHub checks; it does not supply background-shell wake notifications, cloud timers, or active-goal continuation. MCP connectors and service credentials remain external dependencies. Stop the affected workflow at its unmet gate and name what is missing. Do not fabricate equivalent verification or approvals.',
      'Benny is a dormant source pack, not a registered automation. Its Reference reviewed-editor creation and credential-isolation requirements remain unsatisfied by this extension.',
      `This session transcript is ${ctx.sessionManager.getSessionFile() ?? 'in memory'}. Workspace is ${ctx.cwd}.`,
  ].join('\n\n');
}
