import type { Phase } from '../domain/state.ts';

export const TRANSITIONS: { readonly [From in Phase]: readonly Phase[] } = {
  START: ['PREFLIGHT'],
  PREFLIGHT: ['CLASSIFY'],
  CLASSIFY: ['CLARIFY', 'DIAGNOSE', 'EXPLICIT_TRIAGE', 'EXPLICIT_ARCH_REVIEW'],
  EXPLICIT_TRIAGE: ['CLARIFY', 'DIAGNOSE'],
  EXPLICIT_ARCH_REVIEW: ['CLARIFY'],
  CLARIFY: ['DOMAIN'],
  DIAGNOSE: ['DOMAIN'],
  DOMAIN: ['ARCHITECT'],
  ARCHITECT: ['PROTOTYPE', 'DESIGN', 'CONFIRM_TDD_SEAMS'],
  PROTOTYPE: ['ARCHITECT', 'DESIGN', 'CONFIRM_TDD_SEAMS'],
  DESIGN: ['PROTOTYPE', 'CONFIRM_TDD_SEAMS'],
  CONFIRM_TDD_SEAMS: ['BUILD_GRAPH'],
  BUILD_GRAPH: ['IMPLEMENT'],
  IMPLEMENT: ['INTEGRATE', 'ARCHITECT'],
  INTEGRATE: ['REVIEW', 'IMPLEMENT'],
  REVIEW: ['VERIFY', 'IMPLEMENT', 'ARCHITECT', 'DESIGN', 'CONFIRM_TDD_SEAMS'],
  VERIFY: ['FREEZE_REVISION', 'IMPLEMENT', 'DESIGN'],
  FREEZE_REVISION: ['REVERIFY_STALE'],
  REVERIFY_STALE: ['PR_READY', 'IMPLEMENT'],
  PR_READY: ['REVERIFY_STALE'],
};

export function isLegalTransition(from: Phase, to: Phase): boolean {
  return TRANSITIONS[from].includes(to);
}
