import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, expect, test } from 'vitest';
import { runtimeOwner } from '../src/runtime.ts';

const homes: string[] = [];
afterEach(() => {
  for (const home of homes.splice(0)) rmSync(home, { recursive: true, force: true });
});

function home(extension?: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'pi-caveman-home-'));
  homes.push(dir);
  if (extension !== undefined) {
    mkdirSync(join(dir, '.pi/agent/extensions'), { recursive: true });
    writeFileSync(join(dir, '.pi/agent/extensions/caveman-native.js'), extension);
  }
  return dir;
}

test('the package owns the runtime when the CLI manages none', () => {
  expect(runtimeOwner({}, home())).toBe('package');
});

test('a caveman wrap pi launch owns the runtime', () => {
  expect(runtimeOwner({ CAVEMAN_PI_HOOK_CMD: '["caveman"]' }, home())).toBe('caveman-wrap');
});

test('a caveman enable pi extension owns the runtime', () => {
  expect(runtimeOwner({}, home('// caveman:native-pi — GENERATED by `caveman enable pi`.\n'))).toBe('caveman-enable');
});

test('an unrelated caveman-native.js leaves the runtime with the package', () => {
  expect(runtimeOwner({}, home('export default () => {};\n'))).toBe('package');
});

test('an empty hook command leaves the runtime with the package', () => {
  expect(runtimeOwner({ CAVEMAN_PI_HOOK_CMD: '' }, home())).toBe('package');
});
